/// Actions for power points by Bruno Calado

export const POWER_POINT_OPTIONS = [
  {
    id: "CH01PP",
    name: "+1 PP",
    button_name: "+1",
    shotsUsed: "+1",
    selector_type: "item_type",
    selector_value: "power",
    group: "Power Points",
  },
  {
    id: "CH02PP",
    name: "+2 PP",
    button_name: "+2",
    shotsUsed: "+2",
    selector_type: "item_type",
    selector_value: "power",
    group: "Power Points",
  },
  {
    id: "CH03PP",
    name: "+3 PP",
    button_name: "+3",
    shotsUsed: "+3",
    selector_type: "item_type",
    selector_value: "power",
    group: "Power Points",
  },
  {
    id: "CH04PP",
    name: "+4 PP",
    button_name: "+4",
    shotsUsed: "+4",
    selector_type: "item_type",
    selector_value: "power",
    group: "Power Points",
  },
  {
    id: "CH05PP",
    name: "+5 PP",
    button_name: "+5",
    shotsUsed: "+5",
    selector_type: "item_type",
    selector_value: "power",
    group: "Power Points",
  },
  {
    id: "CH06PP",
    name: "+6 PP",
    button_name: "+6",
    shotsUsed: "+6",
    selector_type: "item_type",
    selector_value: "power",
    group: "Power Points",
  },
  {
    id: "CH07PP",
    name: "+7 PP",
    button_name: "+7",
    shotsUsed: "+7",
    selector_type: "item_type",
    selector_value: "power",
    group: "Power Points",
  },
  {
    id: "CH08PP",
    name: "+8 PP",
    button_name: "+8",
    shotsUsed: "+8",
    selector_type: "item_type",
    selector_value: "power",
    group: "Power Points",
  },
  {
    id: "CH09PP",
    name: "+9 PP",
    button_name: "+9",
    shotsUsed: "+9",
    selector_type: "item_type",
    selector_value: "power",
    group: "Power Points",
  },
];
