/// Actions for combat options in the core rulebook

export const COMBAT_OPTIONS = [
    {
        id: "AIM",
        name: "BRSW.Aiming",
        button_name: "BRSW.Aiming",
        skillMod: 2,
        aimingIgnoreMod: 4,
        selector_type: "skill",
        selector_value: "BRSW.Shooting",
        section: "attack",
        group: "BRSW.AttackOption",
        defaultChecked: {
            selector_type: "actor_has_effect",
            selector_value: "BRSW.Aiming",
        },
    },
    {
        id: "WTK",
        name: "BRSW.WildAttack",
        button_name: "BRSW.WildAttack",
        skillMod: 2,
        dmgMod: 2,
        isWildAttack: true,
        selector_type: "skill",
        selector_value: "fighting",
        self_add_status: "vulnerable",
        section: "attack",
        group: "BRSW.AttackOption",
        defaultChecked: {
            selector_type: "actor_has_effect",
            selector_value: "BRSW.StatusEffect.WildAttack",
        },
    },
    {
        id: "DROP",
        name: "BRSW.TheDropName",
        button_name: "BRSW.TheDrop",
        skillMod: 4,
        dmgMod: 4,
        selector_type: "item_has_damage",
        selector_value: "true",
        section: "attack",
        group: "BRSW.SituationalModifiers",
    },
    {
        id: "CS-ARM",
        name: "BRSW.CalledArm",
        button_name: "BRSW.CalledArm",
        skillMod: -2,
        ignoresArcaneActivation: true,
        selector_type: "is_weapon_or_bolt",
        selector_value: "true",
        change_location: "arms",
        section: "attack",
        group: "BRSW.AttackOptionCalledShot",
        group_single: true,
        aiming_ignores: true,
    },
    {
        id: "CS-HAND",
        name: "BRSW.CalledHand",
        button_name: "BRSW.CalledHand",
        skillMod: -4,
        ignoresArcaneActivation: true,
        selector_type: "is_weapon_or_bolt",
        selector_value: "true",
        change_location: "arms",
        section: "attack",
        group: "BRSW.AttackOptionCalledShot",
        group_single: true,
        aiming_ignores: true,
    },
    {
        id: "CS-HEAD",
        name: "BRSW.CalledHead",
        button_name: "BRSW.CalledHead",
        skillMod: -4,
        ignoresArcaneActivation: true,
        dmgMod: +4,
        dmgOverride: "",
        selector_type: "is_weapon_or_bolt",
        selector_value: "true",
        change_location: "head",
        section: "attack",
        group: "BRSW.AttackOptionCalledShot",
        group_single: true,
        aiming_ignores: true,
    },
    {
        id: "CS-LEG",
        name: "BRSW.CalledLeg",
        button_name: "BRSW.CalledLeg",
        skillMod: -2,
        ignoresArcaneActivation: true,
        selector_type: "is_weapon_or_bolt",
        selector_value: "true",
        change_location: "legs",
        section: "attack",
        group: "BRSW.AttackOptionCalledShot",
        group_single: true,
        aiming_ignores: true,
    },
    {
        id: "1-LightCover",
        name: "BRSW.LightCover",
        button_name: "BRSW.LightCover",
        skillMod: "-2",
        ignoresArcaneActivation: true,
        selector_type: "is_weapon_or_bolt",
        selector_value: "true",
        section: "attack",
        group: "BRSW.Cover",
        group_single: true,
        aiming_ignores: true,
    },
    {
        id: "2-MediumCover",
        name: "BRSW.MediumCover",
        button_name: "BRSW.MediumCover",
        skillMod: "-4",
        ignoresArcaneActivation: true,
        selector_type: "is_weapon_or_bolt",
        selector_value: "true",
        section: "attack",
        group: "BRSW.Cover",
        group_single: true,
        aiming_ignores: true,
    },
    {
        id: "3-HeavyCover",
        name: "BRSW.HeavyCover",
        button_name: "BRSW.HeavyCover",
        skillMod: "-6",
        ignoresArcaneActivation: true,
        selector_type: "is_weapon_or_bolt",
        selector_value: "true",
        section: "attack",
        group: "BRSW.Cover",
        group_single: true,
        aiming_ignores: true,
    },
    {
        id: "4-NearTotalCover",
        name: "BRSW.NearTotalCover",
        button_name: "BRSW.NearTotalCover",
        skillMod: "-8",
        ignoresArcaneActivation: true,
        selector_type: "is_weapon_or_bolt",
        selector_value: "true",
        section: "attack",
        group: "BRSW.Cover",
        group_single: true,
        aiming_ignores: true,
    },
    {
        id: "TOUCHATTACK",
        name: "BRSW.TouchAttackName",
        button_name: "BRSW.TouchAttack",
        skillMod: "+2",
        dmgOverride: "0",
        selector_type: "skill",
        selector_value: "fighting",
        section: "attack",
        group: "BRSW.SituationalModifiers",
    },
    {
        id: "NONLETHALDAMAGE",
        name: "BRSW.NonlethalDamageName",
        button_name: "BRSW.NonlethalDamage",
        skillMod: "-1",
        selector_type: "skill",
        selector_value: "fighting",
        section: "attack",
        group: "BRSW.SituationalModifiers",
    },
    {
        id: "IGNORESHIELD",
        name: "BRSW.IgnoreShieldName",
        button_name: "BRSW.IgnoreShield",
        ignoreShield: true,
        selector_type: "is_weapon_or_bolt",
        selector_value: "true",
        section: "attack",
        group: "BRSW.SituationalModifiers",
    },
    {
        id: "AttackInanimateObject",
        name: "BRSW.AttackInanimate",
        button_name: "BRSW.AttackInanimate",
        avoid_exploding_damage: "true",
        or_selector: [
            { selector_type: "item_has_damage", selector_value: "true" },
        ],
        section: "attack",
        group: "BRSW.AttackOption",
    },
    {
        id: "DESPERATE_ATTACK-2",
        name: "Desperate Attack +2",
        button_name: "Desperate Attack +2",
        skillMod: 2,
        dmgMod: -2,
        dmgOverride: "",
        and_selector: [
            {
                selector_type: "skill",
                selector_value: "fighting",
            },
            {
                selector_type: "item_type",
                selector_value: "weapon",
            },
        ],
        section: "attack",
        group: "BRSW.AttackOptionDesperate",
        group_single: true,
    },
    {
        id: "DESPERATE_ATTACK-4",
        name: "Desperate Attack +4",
        button_name: "Desperate Attack +4",
        skillMod: 4,
        dmgMod: -4,
        dmgOverride: "",
        and_selector: [
            {
                selector_type: "skill",
                selector_value: "fighting",
            },
            {
                selector_type: "item_type",
                selector_value: "weapon",
            },
        ],
        section: "attack",
        group: "BRSW.AttackOptionDesperate",
        group_single: true,
    },
];
